# Generated by Django 3.0.4 on 2022-06-01 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='definition',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='words',
            new_name='title',
        ),
    ]
