# Generated by Django 3.0.4 on 2022-06-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20220601_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=140, verbose_name='Book Name')),
                ('book_author', models.CharField(max_length=140, verbose_name='Author Name')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
