# Generated by Django 3.0.4 on 2022-06-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20220602_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_finished',
            field=models.CharField(max_length=100, null=True, verbose_name='Finished Reading Date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.CharField(max_length=10, verbose_name='Author Name'),
        ),
    ]
