# Generated by Django 3.0.4 on 2022-06-03 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_auto_20220603_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
